import { AppLoadContext } from "@remix-run/cloudflare"
import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages"
import { drizzle } from "drizzle-orm/d1"
import schema from "~/db.server/schema"

// @ts-ignore - the server build file is generated by `remix vite:build`
import * as build from "../build/server"

export const onRequest = createPagesFunctionHandler({
  // @ts-ignore - the server build file is generated by `remix vite:build`
  build,

  getLoadContext: async (context): Promise<AppLoadContext> => {
    const db = drizzle(context.context.cloudflare.env.DB as D1Database, {
      schema,
    })
    return {
      db,
      env: context.context.cloudflare.env,
    }
  },
})
