name = "lgtm"

[[d1_databases]]
binding = "DB"
database_name = "lgtm"
database_id = "259c6786-1188-44ad-b2c5-d84174bcc329"
migrations_table = "migrations"
migrations_dir = "./app/db.server/migrations"

[[r2_buckets]]
binding = 'R2'
bucket_name = 'lgtm'
